<?php
/* $Id$ */

/**
 * @file
 * Author: Fredrik Jonsson <fredrik at combonet dot se>
 * A module that adds Digg, del.icio.us, reddit and Technorati links to nodes.
 */

/**
 * Implementation of hook_help().
 */
function service_links_help($section = 'admin/help#service_links') {
  switch ($section) {
    case 'admin/modules#description':
      $output = t('Add Digg, del.icio.us, reddit and Technorati links to nodes.');
      break;
    case 'admin/settings/service_links':
      $output = t('<p>Here you can configure the service links.</p>');
      break;
  }
  return $output;
}

/**
 * Implementation of hook_settings().
 */
function service_links_settings() {

  foreach(node_get_types() as $type => $name) {
    $options[$type] = $name;
  }

  $form['what_links_to_show'] = array(
    '#type' => 'fieldset',
    '#title' => t('What links to show'),
  );
  $form['what_links_to_show']['service_links_show_delicious'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show del.icio.us links'),
    '#return_value' => 1,
    '#default_value' => variable_get('service_links_show_delicious', '1'),
  );
  $form['what_links_to_show']['service_links_show_digg'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show Digg links'),
    '#return_value' => 1,
    '#default_value' => variable_get('service_links_show_digg', '1'),
  );
  $form['what_links_to_show']['service_links_show_reddit'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show Reddit links'),
    '#return_value' => 1,
    '#default_value' => variable_get('service_links_show_reddit', '1'),
  );
  $form['what_links_to_show']['service_links_show_technorati'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show Technorati links'),
    '#return_value' => 1,
    '#default_value' => variable_get('service_links_show_technorati', '1'),
  );

  $form['where_and_how_to_show_the_links'] = array(
    '#type' => 'fieldset',
    '#title' => t('Where and how to show the links'),
  );
  $form['where_and_how_to_show_the_links']['service_links_style'] = array(
    '#type' => 'radios',
    '#title' => t('Link style'),
    '#default_value' => variable_get('service_links_style', 1),
    '#options' => array('1' => t('Text links'),'2' => t('Image links'),'3' => t('Image and text links')),
  );
  $form['where_and_how_to_show_the_links']['service_links_node_types'] = array(
    '#type' => 'select',
    '#title' => t('Node types to display links for'),
    '#default_value' => variable_get('service_links_node_types', array()),
    '#options' => $options,
    '#multiple' => TRUE,
  );
  $form['where_and_how_to_show_the_links']['service_links_main'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show links also on nodes on front page'),
    '#return_value' => 1,
    '#default_value' => variable_get('service_links_main', 0),
  );

  return $form;
}

/**
 * Implementation of hook_link().
 */
function service_links_link($type, $node = 0, $main) {
  $links = array();

  $node_type = in_array($node->type, variable_get('service_links_node_types', array()), TRUE);
  $links_main = variable_get('service_links_main', 0) == '1' || $main == 0 ? '1' : '0';

  if ($type == 'node' && $node_type && $links_main) {
    $url = url("node/$node->nid", NULL, NULL, TRUE);
    $title = drupal_urlencode($node->title);

    if (variable_get('service_links_show_delicious', 1)) {
      $links[] = _service_link_build_link(t('delicious'), "http://del.icio.us/post?url=$url&title=$title", t('Bookmark this post on del.icio.us.'), 'delicious.png');
    }
    if (variable_get('service_links_show_digg', 1)) {
      $links[] = _service_link_build_link(t('digg'), "http://digg.com/submit?phase=2&url=$url", t('Digg this post on digg.com.'), 'digg.png');
    }
    if (variable_get('service_links_show_reddit', 1)) {
      $links[] = _service_link_build_link(t('reddit'), "http://reddit.com/submit?url=$url&title=$title", t('Submit this post on reddit.com.'), 'reddit.png');
    }
    if (variable_get('service_links_show_technorati', 1)) {
      $links[] = _service_link_build_link(t('technorati'), "http://technorati.com/cosmos/search.html?url=$url", t('Search Technorati for links to this post.'), 'technorati.png');
    }
  }

  return $links;
}

function _service_link_build_link($text, $url, $title, $image) {
  global $base_path;

  if (variable_get('service_links_style', 1) == '3') {
    $link = '<a href="'. check_url($url) .'" title="'. $title .'"><img src="'. $base_path . drupal_get_path('module', 'service_links') .'/'. $image .'" alt="'. $text .'" /> '. $text .'</a>';
  }
  elseif (variable_get('service_links_style', 1) == '2') {
    $link = '<a href="'. check_url($url) .'" title="'. $title .'"><img src="'. $base_path . drupal_get_path('module', 'service_links') .'/'. $image .'" alt="'. $text .'" /></a>';
  }
  else {
    $link = '<a href="'. check_url($url) .'" title="'. $title .'">'. $text .'</a>';
  }

  return $link;
}
?>
